/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioneweather;

import java.awt.event.KeyEvent;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
//import java.awt.geom.Ellipse2D;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Wang
 */
public class Grafica extends javax.swing.JFrame {

    private boolean sfondo = true;
    private ArrayList<JSONObject> informazioni = new ArrayList<>();
    private int cont = -1;
    private ArrayList<String> nomi = new ArrayList<>();
    private boolean controllo = true;
    private boolean controlloNome = true;

    /**
     * Creates new form Grafica
     */
    public Grafica() throws IOException {
        setUndecorated(true);//Non decorato

        initComponents();
        
        setTitle("Weather");
        
        //Per arrontondare gli angoli del frame
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 5, 5));

        //Per dare la possibilità di muovere il frame attraverso il cursore del mouse
        MouseAdapter m = new MouseAdapter() {
            int ultimoX, ultimoY;

            @Override
            public void mousePressed(MouseEvent e) {
                ultimoX = e.getXOnScreen();
                ultimoY = e.getYOnScreen();
            }

            @Override
            public void mouseDragged(MouseEvent e) {
                int x = e.getXOnScreen();
                int y = e.getYOnScreen();
                setLocation(getLocationOnScreen().x + x - ultimoX,
                        getLocationOnScreen().y + y - ultimoY);
                ultimoX = x;
                ultimoY = y;
            }
        };
        addMouseListener(m);
        addMouseMotionListener(m);

        //Per cambiare il cursore del mouse quando è sopra ai label
        lblRicerca.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblCestino.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblCambio.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblDestra.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblSinistra.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        lblSinistra1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        //Per arrontondare gli angoli del campo di testo
        Border b = new LineBorder(Color.white, 5, true);
        txtRicerca.setBorder(b);

        //Per impostare l'icona all'applicazione
        Image i = ImageIO.read(getClass().getResource("/gestioneweather/Icone/icona.png"));
        setIconImage(i);
        
        //Per non vedere le frecce
        lblDestra.setEnabled(false);
        lblSinistra.setEnabled(false);
        lblDestra.setVisible(false);
        lblSinistra.setVisible(false);
        lblSinistra1.setEnabled(false);
        lblSinistra1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSinistra1 = new javax.swing.JLabel();
        lblCambio = new javax.swing.JLabel();
        lblCestino = new javax.swing.JLabel();
        lblSinistra = new javax.swing.JLabel();
        lblDestra = new javax.swing.JLabel();
        lblCittà = new javax.swing.JLabel();
        lblRicerca = new javax.swing.JLabel();
        lblTemperatura = new javax.swing.JLabel();
        btnChiudi = new javax.swing.JButton();
        lblImmagine = new javax.swing.JLabel();
        lblVelocità = new javax.swing.JLabel();
        lblDeg = new javax.swing.JLabel();
        lblUmidità = new javax.swing.JLabel();
        lblNubi = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblStato = new javax.swing.JLabel();
        txtRicerca = new javax.swing.JTextField();
        lblSfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSinistra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/sinistra.png"))); // NOI18N
        lblSinistra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSinistra1MouseClicked(evt);
            }
        });
        getContentPane().add(lblSinistra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 40, 40));

        lblCambio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/chiaro.png"))); // NOI18N
        lblCambio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCambioMouseClicked(evt);
            }
        });
        getContentPane().add(lblCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 20, 20));

        lblCestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/cestino.png"))); // NOI18N
        lblCestino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCestinoMouseClicked(evt);
            }
        });
        getContentPane().add(lblCestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 20, 20));

        lblSinistra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/sinistra.png"))); // NOI18N
        lblSinistra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSinistraMouseClicked(evt);
            }
        });
        getContentPane().add(lblSinistra, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 40, 40));

        lblDestra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/destra.png"))); // NOI18N
        lblDestra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDestraMouseClicked(evt);
            }
        });
        getContentPane().add(lblDestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 40, 40));

        lblCittà.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        lblCittà.setText("Città:");
        getContentPane().add(lblCittà, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 301, -1));

        lblRicerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/lente.png"))); // NOI18N
        lblRicerca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRicercaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRicercaMouseEntered(evt);
            }
        });
        getContentPane().add(lblRicerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        lblTemperatura.setFont(new java.awt.Font("Perpetua Titling MT", 1, 48)); // NOI18N
        lblTemperatura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTemperatura.setToolTipText("");
        getContentPane().add(lblTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 301, 105));

        btnChiudi.setBackground(new java.awt.Color(255, 0, 0));
        btnChiudi.setFont(new java.awt.Font("Perpetua Titling MT", 1, 8)); // NOI18N
        btnChiudi.setText("X");
        btnChiudi.setPreferredSize(new java.awt.Dimension(25, 10));
        btnChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiudiActionPerformed(evt);
            }
        });
        getContentPane().add(btnChiudi, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 10, 40, 20));

        lblImmagine.setBackground(new java.awt.Color(255, 255, 255));
        lblImmagine.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblImmagine.setForeground(new java.awt.Color(255, 255, 255));
        lblImmagine.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/Default.png"))); // NOI18N
        getContentPane().add(lblImmagine, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        lblVelocità.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        lblVelocità.setText("Velocità del vento:");
        getContentPane().add(lblVelocità, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 274, 301, -1));

        lblDeg.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        lblDeg.setText("Deg:");
        getContentPane().add(lblDeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 252, 301, -1));

        lblUmidità.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        lblUmidità.setText("Umidità:");
        getContentPane().add(lblUmidità, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 230, 301, -1));

        lblNubi.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        lblNubi.setText("Stato delle nubi:");
        getContentPane().add(lblNubi, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 208, 301, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 192, 250, 10));

        lblStato.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        lblStato.setText("stato:");
        getContentPane().add(lblStato, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 170, 301, -1));

        txtRicerca.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        txtRicerca.setBorder(null);
        txtRicerca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRicercaKeyPressed(evt);
            }
        });
        getContentPane().add(txtRicerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 250, 30));

        lblSfondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Sfondo.png"))); // NOI18N
        getContentPane().add(lblSfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiudiActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnChiudiActionPerformed

    private void lblRicercaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRicercaMouseClicked
        // TODO add your handling code here:
        ricerca();

    }//GEN-LAST:event_lblRicercaMouseClicked

    private void lblRicercaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRicercaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblRicercaMouseEntered

    private void txtRicercaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRicercaKeyPressed
        // TODO add your handling code here:
        //Per iniziare la ricerca utilizzando il tasto invio
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ricerca();
        }
    }//GEN-LAST:event_txtRicercaKeyPressed

    private void lblCambioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambioMouseClicked
        // TODO add your handling code here:
        //Per cambiare lo sfondo
        if (sfondo == true) {
            lblSfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Sfondo2.png")));
            lblCambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/scuro.png")));
            sfondo = false;
        } else {
            lblSfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Sfondo.png")));
            lblCambio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/chiaro.png")));
            sfondo = true;
        }
    }//GEN-LAST:event_lblCambioMouseClicked

    private void lblSinistraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSinistraMouseClicked
        // TODO add your handling code here:
        if (controllo == false) {
            cont--;
            if (cont < 0) {
                cont = 0;
                //JOptionPane.showMessageDialog(null, "Ti trovai all'inizio", "Attenzione", JOptionPane.WARNING_MESSAGE);
            } else {
                JSONObject j = informazioni.get(cont);
                try {
                    settaggio(j, nomi.get(cont));
                } catch (JSONException ex) {
                    Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        //System.out.println(cont);
        controlloFrecce();
    }//GEN-LAST:event_lblSinistraMouseClicked

    private void lblDestraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDestraMouseClicked
        // TODO add your handling code here:
        if (controllo == false) {
            cont++;
            if (cont > informazioni.size() - 1) {
                cont--;
                //JOptionPane.showMessageDialog(null, "Ti trovi alla fine", "Attenzione", JOptionPane.WARNING_MESSAGE);
            } else {
                JSONObject j = informazioni.get(cont);
                try {
                    settaggio(j, nomi.get(cont));
                } catch (JSONException ex) {
                    Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        //System.out.println(cont);
        controlloFrecce();
    }//GEN-LAST:event_lblDestraMouseClicked

    private void lblCestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCestinoMouseClicked
        // TODO add your handling code here:
        //Reiniazializza le variabili/impostazioni
        controlloNome = true;
        controllo = true;
        cont = -1;
        informazioni = new ArrayList<>();
        nomi = new ArrayList<>();
        lblCittà.setText("Città: ");
        lblStato.setText("Stato: ");
        lblTemperatura.setText("");
        lblNubi.setText("Stato delle nubi: ");
        lblUmidità.setText("Umidità: ");
        lblDeg.setText("Deg: ");
        lblVelocità.setText("Velocità del vento: ");
        lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/default.png")));
        lblDestra.setEnabled(false);
        lblDestra.setVisible(false);
        lblSinistra.setEnabled(false);
        lblSinistra.setVisible(false);
        lblSinistra1.setEnabled(false);
        lblSinistra1.setVisible(false);
    }//GEN-LAST:event_lblCestinoMouseClicked

    private void lblSinistra1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSinistra1MouseClicked
        // TODO add your handling code here:
        if (controllo == false) {
            cont--;
            if (cont < 0) {
                cont = 0;
                //JOptionPane.showMessageDialog(null, "Ti trovai all'inizio", "Attenzione", JOptionPane.WARNING_MESSAGE);
            } else {
                JSONObject j = informazioni.get(cont);
                try {
                    settaggio(j, nomi.get(cont));
                } catch (JSONException ex) {
                    Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        //System.out.println(cont);
        controlloFrecce();
    }//GEN-LAST:event_lblSinistra1MouseClicked

    public void controlloFrecce() {
        if (cont == 0 && nomi.size() > 1) {
            lblDestra.setEnabled(true);
            lblDestra.setVisible(true);
            lblSinistra1.setEnabled(false);
            lblSinistra1.setVisible(false);
            lblSinistra.setEnabled(false);
            lblSinistra.setVisible(false);
        }
        if (cont == nomi.size() - 1 && nomi.size() > 1) {
            lblDestra.setEnabled(false);
            lblDestra.setVisible(false);
            lblSinistra1.setEnabled(true);
            lblSinistra1.setVisible(true);
            lblSinistra.setEnabled(false);
            lblSinistra.setVisible(false);
        }
        if (cont > 0 && cont < nomi.size() - 1 && nomi.size() > 1) {
            lblDestra.setEnabled(true);
            lblDestra.setVisible(true);
            lblSinistra.setEnabled(true);
            lblSinistra.setVisible(true);
            lblSinistra1.setEnabled(false);
            lblSinistra1.setVisible(false);
        }
    }

    public void ricerca() {
        String nome = txtRicerca.getText();//Nome della città
        for (int i = 0; i < nomi.size(); i++) {//Controllo della città, se è già presente
            if (nome.equals(nomi.get(i))) {
                controlloNome = false;
                JSONObject j = informazioni.get(i);
                cont = i;
                controlloFrecce();
                
                try {
                    settaggio(j, nomi.get(i));
                } catch (JSONException ex) {
                    Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        String key = "INSERT_KEY";
        
        if (controlloNome == true) {//In caso la città non sia già presente
            URL u = null;
            try {
                u = new URL("http://api.openweathermap.org/data/2.5/weather?q=" + nome + "&appid=" + key);
                System.out.println("Url aperto: " + u);
            } catch (MalformedURLException e) {
                System.out.println("Url errato: " + u);
                System.exit(0);
            }

            URLConnection c = null;

            Scanner urlSc = null;

            try {
                c = u.openConnection();
                c.connect();
                
                try {
                    try {
                   
                        urlSc = new Scanner(c.getInputStream());
                        System.out.println("Connesione avvenuta con successo");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Nome della città non corretto", "Errore", JOptionPane.ERROR_MESSAGE);
                    }
                    JSONObject j = null;

                    controllo = false;

                    while (urlSc.hasNext()) {
                        j = new JSONObject(urlSc.nextLine());//File JSON che contiene tutti i dati
                        informazioni.add(j);
                        nomi.add(nome);
                        cont = nomi.size() - 1;

                        if (cont > 0) {
                            lblSinistra1.setEnabled(true);
                            lblSinistra1.setVisible(true);
                            lblDestra.setEnabled(false);
                            lblDestra.setVisible(false);
                            lblSinistra.setEnabled(false);
                            lblSinistra.setVisible(false);
                        }

                        settaggio(j, nome);

                    }
                } catch (JSONException ex) {
                    JOptionPane.showMessageDialog(null, "Nome della città non corretto", "Errore", JOptionPane.ERROR_MESSAGE);
                    //Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (Exception e) {
                System.out.println("Errore: " + e);
            }
        }

        controlloNome = true;
    }

    public void settaggio(JSONObject j, String nome) throws JSONException {
        JSONArray j2 = null;
        j2 = j.getJSONArray("weather");
        String icona = j2.getJSONObject(0).getString("icon");
        //Per vedere i dati nella console
        System.out.println("Stato di appartenenza:" + j.getJSONObject("sys").getString("country"));
        System.out.println("Temperatura:" + j.getJSONObject("main").getString("temp"));
        System.out.println("Stato delle nubi:" + j.getJSONObject("clouds").getString("all"));
        System.out.println("Umidità:" + j.getJSONObject("main").getString("humidity"));
        System.out.println("Informazioni inerenti al vento:");
        System.out.println("Deg:" + j.getJSONObject("wind").getString("deg"));
        System.out.println("Velocità:" + j.getJSONObject("wind").getString("speed"));

        //Per impostare i dati ottenuti
        lblCittà.setText("Città: " + nome);
        lblStato.setText("Stato: " + j.getJSONObject("sys").getString("country"));
        lblTemperatura.setText((j.getJSONObject("main").getInt("temp") - 273) + "°");
        lblNubi.setText("Stato delle nubi: " + j.getJSONObject("clouds").getString("all"));
        lblUmidità.setText("Umidità: " + j.getJSONObject("main").getString("humidity") + " kg/m³");
        lblDeg.setText("Deg: " + j.getJSONObject("wind").getString("deg"));
        lblVelocità.setText("Velocità del vento: " + j.getJSONObject("wind").getString("speed") + " km/h");

        switch (icona) {//Per cambiare l'icona
            case "01d": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "01n": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "02d": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "02n": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "03d": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "03n": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "04d": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "04n": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "09d": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "09n": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "10d": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "10n": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "11d": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "11n": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "13d": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "13n": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "50d": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            case "50n": {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/" + icona + ".png")));
                break;
            }
            default: {
                lblImmagine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestioneweather/Icone/default.png")));
                break;
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Grafica().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Grafica.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiudi;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblCestino;
    private javax.swing.JLabel lblCittà;
    private javax.swing.JLabel lblDeg;
    private javax.swing.JLabel lblDestra;
    private javax.swing.JLabel lblImmagine;
    private javax.swing.JLabel lblNubi;
    private javax.swing.JLabel lblRicerca;
    private javax.swing.JLabel lblSfondo;
    private javax.swing.JLabel lblSinistra;
    private javax.swing.JLabel lblSinistra1;
    private javax.swing.JLabel lblStato;
    private javax.swing.JLabel lblTemperatura;
    private javax.swing.JLabel lblUmidità;
    private javax.swing.JLabel lblVelocità;
    private javax.swing.JTextField txtRicerca;
    // End of variables declaration//GEN-END:variables
}
